// <auto-generated />
using System;
using KMeeting.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KMeeting.Migrations.Meeting
{
    [DbContext(typeof(MeetingContext))]
    partial class MeetingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KMeeting.DAL.Meeting.MeetingAttendeeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Fullname");

                    b.Property<string>("MeetingEventId");

                    b.Property<string>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("MeetingEventId");

                    b.ToTable("km_attendees");
                });

            modelBuilder.Entity("KMeeting.DAL.Meeting.MeetingEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime>("DayStart");

                    b.Property<int>("MaxPeople");

                    b.Property<string>("Name");

                    b.Property<int>("Status");

                    b.Property<string>("TimeStart");

                    b.HasKey("Id");

                    b.ToTable("km_events");
                });

            modelBuilder.Entity("KMeeting.DAL.Meeting.ProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(true);

                    b.Property<string>("About");

                    b.Property<string>("Email");

                    b.Property<string>("Fullname");

                    b.Property<string>("IdentityId");

                    b.Property<string>("Mobile");

                    b.HasKey("Id");

                    b.ToTable("km_profiles");
                });

            modelBuilder.Entity("KMeeting.DAL.Meeting.MeetingAttendeeEntity", b =>
                {
                    b.HasOne("KMeeting.DAL.Meeting.MeetingEventEntity", "MeetingEvent")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingEventId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
